project:
  type: website

website:
  title: "Arisara's blog"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: posts/welcome/index.qmd
      - icon: github
        href: https://github.com/arisarath
format:
  html:
    theme: minty
    css: styles.css
    bibliography: references.bib
    csl: apa.csl