project:
  type: website
  output-dir: docs

website:
  title: "Arisara's blog"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: index.qmd
      - icon: github
        href: https://github.com/arisarath
format:
  html:
    theme: united
    css: styles.css
    bibliography: references.bib
    csl: apa.csl